import React from 'react';
import { ReportSection, RichNarrative, EvidenceChart, DataComponent, MetricCard, useDataApp } from '../../data-app-public.jsx';
import content from './findings-v2.json';
import './v2-report.css';
const TEAL='#1F6F5C', GREY='#9AA4A0', RED='#B54742';
const figures={
 'monthly-volume-chart':{title:'August fell to 362 quotes; September is incomplete',query:'v2_monthly',plots:[{id:'monthly-volume-chart-plot',query:'v2_monthly',height:235,spec:{type:'line',x:'date',y:'complete_quotes',fields:['complete_quotes','partial_quotes'],colors:{complete_quotes:TEAL,partial_quotes:GREY},legend:{labels:{complete_quotes:'Complete months',partial_quotes:'Partial endpoint'}},valueDecimals:0,stackable:false,annotations:[{id:'import-batch',kind:'event',at:'2024-10-01',field:'import_note',label:'327 records created in one second — suspected import'},{id:'july',kind:'point',at:'2026-07-01',field:'complete_quotes',label:'July: 439'},{id:'august',kind:'point',at:'2026-08-01',field:'complete_quotes',label:'August: 362'},{id:'partial',kind:'point',at:'2026-09-01',field:'partial_quotes',label:'September: 6 through 10 September'}]}}],caption:'24 months • Oct 2024–Sep 2026. Grey endpoint is partial, not a full-month collapse.'},
 'win-rate-chart':{title:'The January–July benchmark is 13%; recent rates are unfinished',query:'v2_win',plots:[{id:'win-rate-plot',query:'v2_win',height:220,spec:{type:'line',x:'date',y:'earlier_win_pct',fields:['earlier_win_pct','recent_win_pct'],colors:{earlier_win_pct:TEAL,recent_win_pct:GREY},legend:{labels:{earlier_win_pct:'Jan–Jul',recent_win_pct:'Aug–Sep: too recent'}},yLabel:'Win rate (%)',valueDecimals:0,stackable:false,showValues:false,annotations:[{id:'august-rate',kind:'point',at:'2026-08-01',field:'recent_win_pct',label:'32% = 20 wins / 63 decided'},{id:'sept-rate',kind:'point',at:'2026-09-01',field:'recent_win_pct',label:'100% = just 2 wins / 2 decided'}]}}],caption:'Wins ÷ decided quotes. Grey starts at July to connect the recent months; July remains in the benchmark.'},
 'drivers-figure':{title:'Australia accounts for −80 quotes; two creators account for −68',query:'v2_country_change',queries:['v2_country_change','v2_creator_change'],plots:[{id:'country-change-plot',title:'By destination',query:'v2_country_change',height:235,spec:{type:'bar',x:'name',y:'quote_change',colors:{Australia:RED,'New Zealand':TEAL},showValues:true,valueDecimals:0}},{id:'creator-change-plot',title:'By creation account',query:'v2_creator_change',height:235,spec:{type:'bar',x:'name',y:'quote_change',colors:{abhisheks:RED,Dhiraj:RED,'All other creators':GREY},showValues:true,valueDecimals:0}}],caption:'August minus July. Each panel sums to −77; these are two views of the same change.'},
 'segments-figure':{title:'Australia and FIT bring more volume; win rates remain close',query:'v2_segments',plots:[{id:'segment-volume-plot',title:'Quotes',query:'v2_segments',height:230,spec:{type:'bar',x:'name',y:'quotes',colors:{quotes:TEAL},showValues:true,valueDecimals:0}},{id:'segment-win-plot',title:'Win rate on decided quotes (%)',query:'v2_segments',height:230,spec:{type:'bar',x:'name',y:'win_pct_rounded',colors:{win_pct_rounded:TEAL},showValues:true,valueDecimals:0}}],caption:'Destination and trip segment are separate comparisons. Do not add their quote counts.'},
 'accounts-figure':{title:'Customer #526083 leads external quoted volume',query:'v2_accounts',plots:[{id:'accounts-plot',query:'v2_accounts',height:315,spec:{type:'horizontalBar',x:'name',y:'quotes',colors:{quotes:TEAL},showValues:true,valueDecimals:0}}],caption:'Top 10 external customers • accepted + rejected + open quotes. #53082 is outside this ranking; 31/31 decided quotes were lost and 7 remain open.'},
 'team-figure':{title:'Recorded calls and work completed differ by assigned caller',query:'v2_team',plots:[{id:'team-calls-plot',title:'Calls logged • 5–18 Aug',query:'v2_team',height:230,spec:{type:'bar',x:'name',y:'calls',colors:{calls:TEAL},showValues:true,valueDecimals:0}},{id:'team-worked-plot',title:'Assigned quote-days worked (%)',query:'v2_team',height:230,spec:{type:'bar',x:'name',y:'worked_pct_rounded',colors:{worked_pct_rounded:TEAL},showValues:true,valueDecimals:0}}],caption:'*Suyash review before named comparisons are circulated. Open book: Hemant 173, Arun 74, Harsh 170, Karthik 100.'},
 'queue-chart':{title:'Carry-over takes 66–88% of the observed follow-up lists',query:'v2_queue',plots:[{id:'queue-plot',query:'v2_queue',height:235,spec:{type:'stackedBar',x:'date',y:'carryover',fields:['carryover','other_followup'],colors:{carryover:RED,other_followup:GREY},legend:{labels:{carryover:'Carry-over',other_followup:'Other follow-up'}},showValues:true,valueDecimals:0}}],caption:'18 August: 146 carry-over + 47 other follow-up = 193. Other follow-up is not necessarily new work. Sundays have no run rows.'},
 'travel-chart':{title:'November and December hold 302 of 643 open future trips',query:'v2_travel',plots:[{id:'travel-plot',query:'v2_travel',height:250,spec:{type:'bar',x:'label',y:'n',colors:{'Nov 2026':TEAL,'Dec 2026':TEAL,'Aug 2026':GREY,'Sep 2026':GREY,'Oct 2026':GREY,'Jan 2027':GREY,'Feb 2027':GREY,'Mar 2027':GREY,'Apr 2027':GREY,'May 2027':GREY,'Jun 2027':GREY,'Jul 2027':GREY,'13+ months':GREY},showValues:true,valueDecimals:0}}],caption:'Open quotes with trips after 18 August. Refresh the list before deciding today’s follow-up priority.'}
};
function download(name,rows){if(!rows.length)return;const cols=Object.keys(rows[0]);const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[cols.map(q).join(','),...rows.map(r=>cols.map(c=>q(r[c])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();URL.revokeObjectURL(url);}
function Table({columns,rows}){return <div className="v2-table" data-reviewed-rows><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{String(v??'—')}</td>)}</tr>)}</tbody></table></div>}
function Narrative({id,text}){return <RichNarrative id={id} value={text}/>}
export function ReportContent(){
 const {snapshot,appTitle,visible}=useDataApp();const rows=id=>snapshot.queries[id]?.rows??[];
 function Figure({id}){const f=figures[id];const qs=f.queries??[f.query];return <div className="v2-figure" data-figure-id={id}><ReportSection id={id} title={f.title} showHeading={f.plots.length>1} queryId={f.query} queryIds={qs} sourceRowsByQuery={Object.fromEntries(qs.map(q=>[q,rows(q)]))}><div className={f.plots.length>1?'v2-plots two':'v2-plots'}>{f.plots.map(p=><EvidenceChart key={p.id} id={p.id} title={p.title??f.title} queryId={p.query} rows={rows(p.query)} sourceRows={rows(p.query)} spec={p.spec} height={p.height}/>)}</div><Narrative id={id+':caption'} text={f.caption}/></ReportSection></div>}
 function Block({b,id}){
  if(b.type==='kpis')return <div className="v2-scorecard" data-figure-id="scorecard-kpis">{content.kpis.map((k,i)=><ReportSection showHeading={false} key={k.label} id={'scorecard-kpi-'+i} queryId="v2_kpis" sourceRows={rows('v2_kpis').slice(i,i+1)} title={k.label} kind="metric"><div className="v2-tile" data-reviewed-rows><p className="v2-tile-label">{k.label}</p><strong>{k.value}</strong><p className="v2-tile-detail">{k.detail}</p></div></ReportSection>)}</div>;
  if(b.type==='text')return <Narrative id={id} text={b.text}/>;
  if(b.type==='table')return <Table columns={b.columns} rows={b.rows}/>;
  return <div className="v2-insight"><Narrative id={id+':story'} text={'### '+b.title+'\n\n'+b.text}/>{b.figure&&<Figure id={b.figure}/>}<div className="v2-action"><Narrative id={id+':action'} text={'**Action & owner:** '+b.action}/></div><div className={'v2-confidence '+b.confidence.toLowerCase()}><Narrative id={id+':confidence'} text={'**Confidence: '+b.confidence+'** — '+b.reason}/></div></div>;
 }
 return <article className="report-content findings-report v2-report"><header className="report-hero"><p className="v2-kicker">SALES INSIGHTS · VERSION 2</p><h1>{appTitle}</h1><Narrative id="review-status" text={content.subtitle}/></header>
 <nav className="findings-nav" aria-label="Report sections">{content.pages.filter(p=>p.id!=='drivers').map(p=><a href={'#section-'+p.id} key={p.id}>{p.section}</a>)}<a href="#appendix-a">Appendices</a></nav>
 {content.pages.map(p=>visible(p.id)&&<section key={p.id} id={'section-'+p.id} data-report-page={p.id} className="v2-page"><ReportSection id={p.id} title={p.title} showHeading={false} queryId={p.queries[0]} queryIds={p.queries} sourceRowsByQuery={Object.fromEntries(p.queries.map(q=>[q,rows(q)]))}><p className="v2-section-label">{p.section}</p><Narrative id={p.id+':heading'} text={'## '+p.title}/>{p.blocks.map((b,i)=><Block key={i} b={b} id={p.id+':block-'+i}/>)}</ReportSection></section>)}
 <section id="appendix-a" className="v2-appendix"><h2>{content.appendices[0].title}</h2><Narrative id="appendix-a:intro" text={content.appendices[0].text}/>{content.issues.map(i=><DataComponent key={i.display_id} id={'evidence-'+i.id} title={i.display_id+' — '+i.title} queryId={i.query} sourceRows={rows(i.query)} displayRows={rows(i.query)} kind="table"><details className="v2-issue"><summary>{i.display_id} — {i.title} · {i.count.toLocaleString()} affected</summary><Narrative id={i.display_id+':detail'} text={'**Count:** '+i.count.toLocaleString()+' / '+i.denominator.toLocaleString()+' ('+i.percent.toFixed(2)+'%). **Severity:** '+i.severity+'.\n\n'+i.meaning+'\n\n**Recommendation:** '+i.action}/><Table columns={Object.keys(rows(i.query)[0]??{})} rows={rows(i.query).slice(0,2).map(r=>Object.values(r))}/><button className="extract-button" onClick={()=>download(i.id,rows(i.query))}>Download all {i.count.toLocaleString()} affected rows</button></details></DataComponent>)}</section>
 <section id="appendix-b" className="v2-appendix"><ReportSection id="appendix-b-method" title={content.appendices[1].title} queryId="source_inventory" queryIds={['source_inventory','date_ranges','v2_kpis']} sourceRowsByQuery={{source_inventory:rows('source_inventory'),date_ranges:rows('date_ranges'),v2_kpis:rows('v2_kpis')}}><Narrative id="appendix-b:method" text="Seven unchanged CRM exports were analysed. Quote performance uses 9,935 non-deleted quotes; quality checks use all 9,973. Created dates span 16 September 2024–10 September 2026; queue runs span 25 June–31 August. There is no verified common extraction timestamp. V2 shows 24 months from October 2024; the preceding partial month remains in the source series. All rates, filters and calculations are inspectable through the chart source controls."/><Table columns={['Export','Rows','SHA256']} rows={rows('source_inventory').map(r=>[r.file,r.rows,r.sha256])}/><Narrative id="appendix-b:definitions" text="**Win rate:** current accepted, including later delivery/accounting stages, divided by accepted plus manually rejected (including rejection after confirmation). Auto Rejected and unresolved are excluded. **Open book:** current Created/Requote. **Assigned caller:** latest available queue assignment, with creator fallback. **Worked:** a logged outcome or qualifying stage event on a surfaced quote-day, potentially by someone other than its assigned caller. **FIT/Groups:** quote-number suffix, not a product catalogue. **Country:** destination, not customer origin. **Backlog:** the existing 18 August carry-over calculation, not a time-valid reconstruction.\n\nBaseline dashboard: Treat as today 18 August 2026; all four callers; per-person series; team charts 5–18 August, with Sundays omitted. The original trip-window CSV contains 791 non-deleted quotes with trips 1 August–31 October. Quality samples exclude direct contact details. All v1 evidence remains in the companion review pack; four implementation findings and the internal-account scope note are supplied separately to Suyash."/><button className="extract-button" onClick={()=>download('source_inventory',rows('source_inventory'))}>Download source inventory</button></ReportSection></section>
 <section id="appendix-c" className="v2-appendix"><h2>{content.appendices[2].title}</h2><Narrative id="appendix-c:intro" text={content.appendices[2].text}/>{content.support.map((s,i)=><details className="v2-support" key={i}><summary>{s.title}</summary><ReportSection id={'support-source-'+i} title={s.title} showHeading={false} queryId={s.queries[0]} queryIds={s.queries} sourceRowsByQuery={Object.fromEntries(s.queries.map(q=>[q,rows(q)]))}><Narrative id={'appendix-c:support-'+i} text={s.text}/></ReportSection></details>)}<details className="v2-support"><summary>Detailed panel calculations and evidence</summary><Table columns={['Panel','Observation','Evidence']} rows={content.panels.map(p=>[p.panel,p.finding,p.evidence_query])}/></details></section></article>;
}
